=== simonisaac/nodeservice/nodeservice.transform.excel/src/main/resources/xsd/nodeExcelSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:map="http://excel.transform.nodeservice.sri.org" targetNamespace="http://excel.transform.nodeservice.sri.org"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="sheetDefinition" type="map:Sheet" />

	<xs:complexType name="Sheet">
		<xs:sequence>
			<xs:element type="xs:string" name="sheetName"/>
			<xs:element type="xs:string" name="sheetId"/>
			<xs:element type="xs:string" name="sheetRootNodeType"/>
			<xs:element type="xs:string" name="sheetNodeType"/>
			<xs:element type="xs:string" name="sheetDescription"/>
			<xs:element type="xs:int" name="startRow" /> <!-- 0 = First Row -->
			<xs:element type="xs:int" name="endRow" minOccurs="0"/>
			<xs:element type="map:ColumnType" name="column" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ColumnType">
		<xs:sequence>
			<xs:element type="xs:int" name="columnIndex"/> <!-- 0 = First Row -->			
			<xs:element type="xs:string" name="columnName" />
			<xs:element type="xs:boolean" name="dateType" minOccurs="0"/>
			<xs:element type="xs:boolean" name="timeType" minOccurs="0"/>			
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== simonisaac/nodeservice/nodeservice.transform.excel/src/test/resources/xml/test3-B.xml
<?xml version="1.0" encoding="UTF-8"?>
<map:sheetDefinition xmlns:map="http://excel.transform.nodeservice.sri.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://excel.transform.nodeservice.sri.org nodeExcelSchema.xsd ">
  <map:sheetName>testSheet</map:sheetName>
  <map:sheetId>testSheet-3</map:sheetId>
  <map:sheetRootNodeType>testSheetRoot</map:sheetRootNodeType>
  <map:sheetNodeType>test3SheetType</map:sheetNodeType>
  <map:sheetDescription>test3 Description</map:sheetDescription>
  <map:startRow>4</map:startRow>
  <map:endRow>9</map:endRow>
  
  <map:column>
    <map:columnIndex>0</map:columnIndex>
    <map:columnName>A - String</map:columnName>
  </map:column>
  
  <map:column>
    <map:columnIndex>1</map:columnIndex>
    <map:columnName>B - Number</map:columnName>
  </map:column>
  
  <map:column>
    <map:columnIndex>2</map:columnIndex>
    <map:columnName>C - Decimal</map:columnName>
  </map:column>
  
  <map:column>
    <map:columnIndex>3</map:columnIndex>    
    <map:columnName>D - Date</map:columnName>
    <map:dateType>true</map:dateType>
  </map:column>
  
</map:sheetDefinition>

=== simonisaac/nodeservice/nodeservice.transform.excel/src/test/resources/xml/test3.xml
<?xml version="1.0" encoding="UTF-8"?>
<map:sheetDefinition xmlns:map="http://excel.transform.nodeservice.sri.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://excel.transform.nodeservice.sri.org nodeExcelSchema.xsd ">
	<map:sheetName>testSheet</map:sheetName>
	<map:sheetId>testExcel-1</map:sheetId>
	<map:sheetRootNodeType>testExcel</map:sheetRootNodeType>
	<map:sheetNodeType>test3SheetType</map:sheetNodeType>
	<map:sheetDescription>test3 Description</map:sheetDescription>
	<map:startRow>1</map:startRow>
	<map:endRow>12</map:endRow>

	<map:column>
		<map:columnIndex>0</map:columnIndex>
		<map:columnName>A - String</map:columnName>
	</map:column>

	<map:column>
		<map:columnIndex>1</map:columnIndex>
		<map:columnName>B - Number</map:columnName>
	</map:column>

	<map:column>
		<map:columnIndex>2</map:columnIndex>
		<map:columnName>C - Decimal</map:columnName>
	</map:column>

	<map:column>
		<map:columnIndex>3</map:columnIndex>
		<map:columnName>D - Date</map:columnName>
		<map:dateType>true</map:dateType>
	</map:column>

	<map:column>
		<map:columnIndex>4</map:columnIndex>
		<map:columnName>E - Pound</map:columnName>
	</map:column>
	
	<map:column>
		<map:columnIndex>5</map:columnIndex>
		<map:columnName>F - Formula</map:columnName>
	</map:column>
	
	<map:column>
		<map:columnIndex>6</map:columnIndex>
		<map:columnName>G - Text</map:columnName>
	</map:column>
	
	<map:column>
		<map:columnIndex>7</map:columnIndex>
		<map:columnName>H - String Formula</map:columnName>
	</map:column>
	
	<map:column>
		<map:columnIndex>8</map:columnIndex>
		<map:columnName>I - Time Type</map:columnName>
		<map:timeType>true</map:timeType>
	</map:column>

</map:sheetDefinition>

=== simonisaac/nodeservice/nodeservice.transform.excel/src/test/resources/xml/ids.xml
<?xml version="1.0" encoding="UTF-8"?>
<map:sheetDefinition xmlns:map="http://excel.transform.nodeservice.sri.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://excel.transform.nodeservice.sri.org nodeExcelSchema.xsd ">
  <map:sheetName>IDS</map:sheetName>
  <map:sheetId>IDSheet-1</map:sheetId>
  <map:sheetRootNodeType>RootIDSSheetType</map:sheetRootNodeType>
  <map:sheetNodeType>IDSSheetType</map:sheetNodeType>
  <map:sheetDescription>IDS Description</map:sheetDescription>
  <map:startRow>1</map:startRow>
  <map:endRow>7</map:endRow>
  
  <map:column>
    <map:columnIndex>0</map:columnIndex>    
    <map:columnName>ID</map:columnName>   
  </map:column>
  
  <map:column>
    <map:columnIndex>1</map:columnIndex>    
    <map:columnName>Name</map:columnName>    
  </map:column>
  
  <map:column>
    <map:columnIndex>2</map:columnIndex>    
    <map:columnName>DoB</map:columnName>
    <map:dateType>true</map:dateType>
  </map:column>
</map:sheetDefinition>
