=== simonisaac/nodeservice/nodeservice.core/src/main/resources/xsd/languageDef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://model.service.nodedef.core.nodeservice.sri.org" targetNamespace="http://model.service.nodedef.core.nodeservice.sri.org"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="languageDef" type="languageDefTO" />

	<xs:complexType name="languageDefTO">
		<xs:sequence>
			<xs:element name="description" type="xs:string" />
			<xs:element name="nodeDef" type="nodeDefTO" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="typeExDef" type="typeExDefTO" maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="nodeDefTO">
		<xs:sequence>
			<xs:element name="id" type="xs:string" />
			<xs:element name="attributes" type="attrDefMap" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="childSetDefs" type="nodeSetDefMap" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="attrDefMap">
		<xs:sequence>
			<xs:element name="id" type="xs:string" />
			<xs:element name="attrDef" type="attrDefTO" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="attrDefTO">
		<xs:sequence>
			<xs:element name="id" type="xs:string" />
			<xs:element name="typeId" type="xs:string" />
			<xs:element name="label" type="xs:string" />
			<xs:element name="defaultValue" type="xs:string" />
			<xs:element name="mandatory" type="xs:boolean" />
			<xs:element name="readonly" type="xs:boolean" />
			<xs:element name="constraints" type="typeConstraintDefTO" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeConstraintDefTO">
		<xs:sequence>
			<xs:element name="id" type="xs:string" />
			<xs:element name="applicableTypes" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="parameterList" type="typeConstraintParameterTO" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeConstraintParameterTO">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="value" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="nodeSetDefMap">
		<xs:sequence>
			<xs:element name="id" type="xs:string" />
			<xs:element name="nodeSetDef" type="nodeSetDefTO" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="nodeSetDefTO">
		<xs:sequence>
			<xs:element name="id" type="xs:string" />
			<xs:element name="nodeType" type="xs:string" />
			<xs:element name="minOccurances" type="xs:int" />
			<xs:element name="maxOccurances" type="xs:int" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeExDefTO">
		<xs:sequence>
			<xs:element name="id" type="xs:string" />
			<xs:element name="parentId" type="xs:string" />
			<xs:element name="constraints" type="typeConstraintDefTO" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== simonisaac/nodeservice/nodeservice.core.nodemgr/src/test/resources/xml/languageDefHierarchy.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:languageDef
	xmlns:p="http://model.service.nodedef.core.nodeservice.sri.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://model.service.nodedef.core.nodeservice.sri.org languageDef.xsd ">

	<p:nodeDef>
		<p:id>childnode</p:id>
		<p:attributes>
			<p:id>string</p:id>
			<p:attrDef>
				<p:id>string</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
	</p:nodeDef>

	<p:nodeDef>
		<p:id>simpleHierachyDef</p:id>
		<p:attributes>
			<p:id>string</p:id>
			<p:attrDef>
				<p:id>string</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>

		<p:childSetDefs>
			<p:id>childnodes</p:id>
			<p:nodeSetDef>
				<p:id>childnodes</p:id>
				<p:nodeType>childnode</p:nodeType>
				<p:minOccurances>3</p:minOccurances>
				<p:maxOccurances>5</p:maxOccurances>
			</p:nodeSetDef>
		</p:childSetDefs>
	</p:nodeDef>

</p:languageDef>

=== simonisaac/nodeservice/nodeservice.core.nodemgr/src/test/resources/xml/languageDef.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:languageDef
	xmlns:p="http://model.service.nodedef.core.nodeservice.sri.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://model.service.nodedef.core.nodeservice.sri.org languageDef.xsd ">
	
	<p:nodeDef>
		<p:id>simpleNodeDef</p:id>
		
		<p:attributes>
			<p:id>string</p:id>
			<p:attrDef>
				<p:id>string</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>true</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
		<p:attributes>
			<p:id>stringMin10</p:id>
			<p:attrDef>
				<p:id>stringMin10</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String Min 10</p:label>
				<p:defaultValue>0123456789</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
				<p:constraints>
					<p:id>MIN_LENGTH</p:id>					
					<p:parameterList>
						<p:name>minLength</p:name>
						<p:value>10</p:value>
					</p:parameterList>
				</p:constraints>
			</p:attrDef>
		</p:attributes>
		<p:attributes>
			<p:id>stringMax20</p:id>
			<p:attrDef>
				<p:id>stringMax20</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String Max 20</p:label>
				<p:defaultValue>01234567890123456789</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
				<p:constraints>
					<p:id>MAX_LENGTH</p:id>					
					<p:parameterList>
						<p:name>maxLength</p:name>
						<p:value>20</p:value>
					</p:parameterList>
				</p:constraints>
			</p:attrDef>
		</p:attributes>
		<p:attributes>
			<p:id>stringExMin5Max10</p:id>
			<p:attrDef>
				<p:id>stringExMin5Max10</p:id>
				<p:typeId>STRING_TYPE_MIN_5</p:typeId>
				<p:label>A String Min5 Max10</p:label>
				<p:defaultValue>012345678</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
				<p:constraints>
					<p:id>MAX_LENGTH</p:id>					
					<p:parameterList>
						<p:name>maxLength</p:name>
						<p:value>10</p:value>
					</p:parameterList>
				</p:constraints>
			</p:attrDef>
		</p:attributes>
		<p:attributes>
			<p:id>long</p:id>
			<p:attrDef>
				<p:id>long</p:id>
				<p:typeId>LONG</p:typeId>
				<p:label>A Long</p:label>
				<p:defaultValue>1</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
		
	</p:nodeDef>
	
	<p:typeExDef>
		<p:id>STRING_TYPE_MIN_5</p:id>
		<p:parentId>STRING</p:parentId>
		<p:constraints>
			<p:id>MIN_LENGTH</p:id>
			<p:parameterList>
				<p:name>minLength</p:name>
				<p:value>5</p:value>
			</p:parameterList>
		</p:constraints>
	</p:typeExDef>
	
</p:languageDef>

=== simonisaac/nodeservice/nodeservice.transform.excel/src/test/resources/spreadsheettests/simple/simpleLanguageDef.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:languageDef
	xmlns:p="http://model.service.nodedef.core.nodeservice.sri.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://model.service.nodedef.core.nodeservice.sri.org languageDef.xsd ">

	<p:nodeDef>
		<p:id>test3SheetType</p:id>
		
		<p:attributes>
			<p:id>A - String</p:id>
			<p:attrDef>
				<p:id>A - String</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
		
		<p:attributes>
			<p:id>B - Number</p:id>
			<p:attrDef>
				<p:id>B - Number</p:id>
				<p:typeId>LONG</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
		
		<p:attributes>
			<p:id>C - Decimal</p:id>
			<p:attrDef>
				<p:id>C - Decimal</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
		
		<p:attributes>
			<p:id>D - Date</p:id>
			<p:attrDef>
				<p:id>D - Date</p:id>
				<p:typeId>DATE</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
		
		<p:attributes>
			<p:id>E - Pound</p:id>
			<p:attrDef>
				<p:id>E - Pound</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
		
		<p:attributes>
			<p:id>F - Formula</p:id>
			<p:attrDef>
				<p:id>F - Formula</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
				
		<p:attributes>
			<p:id>G - Text</p:id>
			<p:attrDef>
				<p:id>G - Text</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
		
		<p:attributes>
			<p:id>H - String Formula</p:id>
			<p:attrDef>
				<p:id>H - String Formula</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
		
		<p:attributes>
			<p:id>I - Time Type</p:id>
			<p:attrDef>
				<p:id>I - Time Type</p:id>
				<p:typeId>STRING</p:typeId>
				<p:label>A String</p:label>
				<p:defaultValue>A String Value</p:defaultValue>
				<p:mandatory>false</p:mandatory>
				<p:readonly>false</p:readonly>
			</p:attrDef>
		</p:attributes>
		
	</p:nodeDef>

	<p:nodeDef>
		<p:id>testExcel</p:id>

		<p:childSetDefs>
			<p:id>rows</p:id>
			<p:nodeSetDef>
				<p:id>rows</p:id>
				<p:nodeType>test3SheetType</p:nodeType>
				<p:minOccurances>1</p:minOccurances>
				<p:maxOccurances>-1</p:maxOccurances>
			</p:nodeSetDef>
		</p:childSetDefs>
	</p:nodeDef>

</p:languageDef>
